[build]
  command = "node remove-all-babel-configs.js && node fix-jsx-runtime.js && node netlify-build-debug.js && rm -f package-lock.json && npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  CI = "true"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY = "true"

[functions]
  directory = "netlify/functions"

# Disable Next.js plugin for static export
# This is handled by static export instead

[context.production.environment]
	  NEXT_PUBLIC_ADMIN_PASSWORD_HASH = "1962eb5a00a85ef6688f12ba5c2d5551d50da4c07d64b46fa1a9e1ae5076674f"
	  NEXT_PUBLIC_AUTH_SALT = "b84997540de9ae822a6aa27e333cd8c8ce6b79079cf448ff6b8a027a845a666b"
	  NEXT_PUBLIC_ADMIN_EMAIL = "aburakan4551@gmail.com"
	  NEXT_PUBLIC_ADMIN_SESSION_DURATION = "3600000"
	  NEXT_PUBLIC_MAX_LOGIN_ATTEMPTS = "5"
	  NEXT_PUBLIC_LOCKOUT_DURATION = "900000"
	  NODE_ENV = "production"

	  # Firebase Configuration (add your actual values)
	  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBCTEmastiOgvmTDu1EHxA0bkDAws00bIU"
	  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "colorstests-573ef.firebaseapp.com"
	  NEXT_PUBLIC_FIREBASE_DATABASE_URL = "https://colorstests-573ef.firebaseio.com"
	  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "colorstests-573ef"
	  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "colorstests-573ef.appspot.com"
	  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "94361461929"
	  NEXT_PUBLIC_FIREBASE_APP_ID = "1:94361461929:web:b34ad287c782710415f5b8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' https://www.gstatic.com https://www.googleapis.com https://accounts.google.com https://*.firebaseio.com https://*.firebaseapp.com https://firebase.googleapis.com https://firebaseinstallations.googleapis.com https://colorstests-573ef.firebaseio.com https://colorstests-573ef-default-rtdb.firebaseio.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com; img-src 'self' data: https: blob: https://*.firebaseapp.com https://*.googleapis.com; font-src 'self' data: https://fonts.gstatic.com https://fonts.googleapis.com; connect-src 'self' https://api.stcpay.com.sa https://*.firebaseio.com https://*.googleapis.com https://*.firebaseapp.com https://firebaseinstallations.googleapis.com https://firebaseremoteconfig.googleapis.com https://firebase.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://www.googleapis.com wss://*.firebaseio.com https://colorstests-573ef.firebaseio.com https://colorstests-573ef-default-rtdb.firebaseio.com; worker-src 'self' blob:; child-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self' https://api.stcpay.com.sa https://accounts.google.com; frame-ancestors 'none'; upgrade-insecure-requests;"

[[redirects]]
  from = "/"
  to = "/ar"
  status = 302

[[redirects]]
  from = "/admin"
  to = "/ar/admin"
  status = 302

[[redirects]]
  from = "/ar/*"
  to = "/ar/:splat"
  status = 200

# API endpoints to Netlify Functions
[[redirects]]
  from = "/api/sessionLogin"
  to = "/.netlify/functions/sessionLogin"
  status = 200

[[redirects]]
  from = "/api/sessionLogout"
  to = "/.netlify/functions/sessionLogout"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/ar/:splat"
  status = 200
