[build]
  command = "node simple-build.js"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY = "true"

[[redirects]]
  from = "/"
  to = "/ar"
  status = 302

[[redirects]]
  from = "/admin"
  to = "/ar/admin"
  status = 302

[[redirects]]
  from = "/ar/*"
  to = "/ar/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/ar/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
